### ISSUE TITLE
Fails with Regexp-Grammars-1.043

### ISSUE THREAD

**Issue by andk** [kentnl/Regexp-Grammars-Common-String#1]
To be precise: fails with DCONWAY/Regexp-Grammars-1.043.tar.gz

Downgrading to 1.042 does as a workaround.

HTH&&Thanks,

**Comment by kentfredric** [comment]
My investigating suggests that one of the undocumented changes in `Regexp::Grammars` in 1.043 introduced something where it forgets to export `$MATCH` as a variable in the callers context.

So now `$MATCH` no longer exists and causes a compile failure.

Writing 

``` perl
our $MATCH
```

Before the grammars definition seems to get around the problem while retaining the desired behaviour.

**Comment by kentfredric** [comment]
https://rt.cpan.org/Ticket/Display.html?id=110356

**Comment by kentfredric** [comment]
Should work now either by upgrading to R:G:C:S@1.000002 or R:G@1.044
